"""add_carbon_credits_fields_to_solar_panel

Revision ID: 4b023cda65ae
Revises: 8299ce7cfc6e
Create Date: 2025-09-27 17:27:18.289605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b023cda65ae'
down_revision = '8299ce7cfc6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solar_panel_applications', sa.Column('carbon_credits_data', sa.Text(), nullable=True))
    op.add_column('solar_panel_applications', sa.Column('carbon_coins_issued', sa.Float(), nullable=True))
    op.add_column('solar_panel_applications', sa.Column('calculation_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solar_panel_applications', 'calculation_date')
    op.drop_column('solar_panel_applications', 'carbon_coins_issued')
    op.drop_column('solar_panel_applications', 'carbon_credits_data')
    # ### end Alembic commands ###
