"""add_forestationapplication_table_v2

Revision ID: 51afce80b5c9
Revises: c04af0cd278e
Create Date: 2025-09-27 04:41:51.155936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51afce80b5c9'
down_revision = 'c04af0cd278e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forestation_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('aadhar_card', sa.String(), nullable=False),
    sa.Column('ownership_document_path', sa.String(), nullable=True),
    sa.Column('geotag_photo_path', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forestation_applications_id'), 'forestation_applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forestation_applications_id'), table_name='forestation_applications')
    op.drop_table('forestation_applications')
    # ### end Alembic commands ###
