"""add_marketplace_credits_table

Revision ID: 8299ce7cfc6e
Revises: b4b3a1bbc5b0
Create Date: 2025-09-27 14:37:40.956812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8299ce7cfc6e'
down_revision = 'b4b3a1bbc5b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solar_panel_applications', 'calculation_date')
    op.drop_column('solar_panel_applications', 'carbon_credits_data')
    op.drop_column('solar_panel_applications', 'carbon_coins_issued')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solar_panel_applications', sa.Column('carbon_coins_issued', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True))
    op.add_column('solar_panel_applications', sa.Column('carbon_credits_data', sa.TEXT(), nullable=True))
    op.add_column('solar_panel_applications', sa.Column('calculation_date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
