"""add_forestationapplication_table

Revision ID: c04af0cd278e
Revises: b4d79425bd1d
Create Date: 2025-09-27 04:40:54.515839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04af0cd278e'
down_revision = 'b4d79425bd1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solar_panel_applications', 'credits_issued')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solar_panel_applications', sa.Column('credits_issued', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
